[package]
name = "dojo_beacon_macros"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
bigdecimal = "0.4.5"
cairo-lang-macro = "0.1.1"
cairo-lang-parser = "2.9.2"
cairo-lang-syntax = "2.9.2"
cairo-lang-defs = "=2.9.2"
cairo-lang-diagnostics = "2.9.2"
cairo-lang-utils = "=2.9.2"
serde = { version = "1.0", features = ["derive"] }
starknet = "0.12.0"
indoc = "2"
dojo-lang = { git = "https://github.com/dojoengine/dojo/", tag = "v1.2.1" }

[workspace]
